Repository terraform-providers/terraform-provider-influxdb, pull requests merged in 2019-01, with the labels that each got.

#15 [AUTOMATED] Upgrade to Go 1.11
  .travis.yml
  README.md
  influxdb/continuous_query.go
  influxdb/continuous_query_test.go
  influxdb/provider.go
  influxdb/resource_database.go
  influxdb/resource_database_test.go
  influxdb/resource_user.go
  influxdb/resource_user_test.go
Labels: size/M

#16 Update readme to match actual code.
  website/docs/index.html.markdown
Labels: documentation, size/XS

#17 Hash and sensitive passwords
  influxdb/provider.go
  influxdb/resource_user.go
  influxdb/utils.go
Labels: size/XS
